# This is a basic workflow to help you get started with Actions

name: auto release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
